name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,E231,E501,W503,E203"
          max-line-length: "88"
          path: "src"
          plugins: "flake8-bugbear==22.1.11 flake8-black"
